const getProductsTypes = {
    FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
    FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
    ADD_PRODUCT_CATEGORY: "ADD_PRODUCT_CATEGORY"
};

export default getProductsTypes;