const paginationTypes = {
    PAGINATION_NUMBER: 'PAGINATION_NUMBER',
    TOTAL_ITEMS_PER_PAGE: 'TOTAL_ITEMS_PER_PAGE',
    TOTAL_NUMBER_OF_PAGES: 'TOTAL_NUMBER_OF_PAGES',
    SHOW_ALL_ITEMS: 'SHOW_ALL_ITEMS'
}

export default paginationTypes