const cartItemsTypes = {
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    CART_ITEMS_NUMBER: "CART_ITEMS_NUMBER",
    UPDATE_CART_ITEMS: "UPDATE_CART_ITEMS",
    TOTAL_SUM: "TOTAL_SUM",
    FETCH_PRODUCTS: "FETCH_PRODUCTS"
}

export default cartItemsTypes