const cartItemsTypes = {
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    CART_ITEMS_NUMBER: "CART_ITEMS_NUMBER",
    UPDATE_CART_ITEMS: "UPDATE_CART_ITEMS",
    TOTAL_SUM: "TOTAL_SUM",
    ALL_PRODUCT_ITEMS: "ALL_PRODUCT_ITEMS"
}

export default cartItemsTypes